export const experience = [
  {
    company: "Mindtickle",
    role: "Software Engineering Intern",
    period: "Oct 2025 — Present",
    summary: "Building async bulk operations infrastructure for enterprise admins, handling up to 500K learners across distributed gRPC services on AWS.",
    details: [
      "Built an async Bulk modules/learners settings update feature for enterprise admins in a team of 3 — server-side filter/selection resolution with fan-out execution via AWS Step Functions + Lambda, handling up to 500K learners and 100+ modules in a single operation.",
      "Implemented multi-level batched pipelines in Go with concurrency and idempotent retries across 10+ gRPC services, reducing manual admin effort from hours to minutes.",
      "Integrated the Bulk Actions feature into the existing audit logging system for all setting updates and built real-time progress tracking end-to-end, giving admins live visibility into long-running bulk jobs.",
      "Debugged production issues in live systems and contributed to serverless CI/CD pipelines for Lambda deployments.",
    ],
    links: [],
    logo: "/mindtickle.png",
    companyWebsite: "https://www.mindtickle.com",
    companyTwitter: "https://x.com/mindtickle",
    tags: ["Go", 'typescript', "AWS Lambda", "Step Functions", "S3", "gRPC", "GitLab CI/CD"],
  },
  // {
  //   company: "Morphle Labs (YC W20)",
  //   role: "Software Engineering Intern",
  //   period: "Oct 2025 — Jan 2026",
  //   summary: "Optimizing multithreaded robot execution pipelines and building internal performance tooling at a YC-backed digital pathology company.",
  //   details: [
  //     "Optimized Robotome's multithreaded execution pipeline by analyzing parallel task behavior, identifying bottlenecks, and increasing true concurrent execution to make the robot faster and more reliable.",
  //     "Built an internal task-flow visualization tool that maps execution sequences using graphs and charts, enabling engineers to trace threading issues, understand dependencies, and significantly accelerate performance tuning.",
  //   ],
  //   links: [],
  //   logo: "/morphle.png",
  //   companyWebsite: "https://morphle.com",
  //   companyTwitter: "",
  //   tags: ["Python", "TypeScript", "React", "WebSockets", "Jenkins"],
  // },
  {
    company: "Verly",
    role: "Co-Founder",
    period: "Oct 2025 — Apr 2026",
    summary: "Built and shipped an AI customer support platform from scratch — solo across product, engineering, marketing, and sales. Acquired real paying customers.",
    details: [
      "Built Verly from scratch: a multi-channel AI customer support platform with website chat, WhatsApp Business, and voice AI agents — all sharing a unified knowledge base with 72% auto-resolution across channels.",
      "Handled everything solo: product design, full-stack engineering, customer acquisition, pricing, and go-to-market strategy.",
      "Implemented enterprise features including smart escalation with full conversation context handoff, continuous learning from every interaction, and integrations with HubSpot, Slack, and Zendesk.",
      "Acquired paying customers at $29.99/month. Wound down after 6 months — product worked, market was harder than expected.",
    ],
    links: [],
    logo: "/verly.png",
    companyWebsite: "https://verlyai.xyz",
    companyTwitter: "",
    tags: ["Next.js", "Python", "LangGraph", "WebSockets", "OpenAI", "WhatsApp API", "Voice AI", "AWS"],
  },
  {
    company: "Trench Exchange",
    role: "Founding Backend Engineer",
    period: "May 2025 — Oct 2025",
    summary: "Developed automated trading services and optimized databases for high-performance Solana DEX operations.",
    details: [
      "Worked on building backend infrastructure for high performance Solana DEX.",
      "Developed a fully automated event-driven trading service with 20+ configurations, achieving transaction confirmation within 1 second and identifying triggered transactions in under 100ms, with a thread-safe, in-memory cache for high-performance data access.",
      "Migrated ClickHouse database to a hybrid ClickHouse and PostgreSQL schema, reducing average API response time by 70% through optimized read queries.",
      "Built upstream Go services to ingest Solana blockchain transactions within 15ms, using gRPC for high-concurrency processing.",
    ],
    links: [],
    logo: "/trench.png",
    companyWebsite: "https://trench.ag",
    companyTwitter: "https://x.com/TrenchExchange",
    tags: ["Go", "Ts", "Web3", "PostgreSQL", "ClickHouse", "AWS", "Redis", "Infra"],
  },
  {
    company: "Heizen (Opengig)",
    role: "SDE Intern (Remote)",
    period: "Feb 2025 — May 2025",
    summary: "Led backend development of multi-agent GenAI applications and automated business development pipelines.",
    details: [
      "Led backend development of multi-agent GenAI applications for Heizen's internal developer assistant suite (coding, design, and product agents), building custom MCP servers with FastAPI and NestJS.",
      "Developed a multi-agent LLM pipeline to automate lead generation, pitch writing, and email outreach for the company's business development team.",
    ],
    links: [],
    logo: "/heizen.png",
    companyWebsite: "https://www.heizen.work",
    companyTwitter: "https://x.com/HeizenOfficial",
    tags: ["FastAPI", "NestJS", "Python", "TypeScript", "LangGraph", "PostgreSQL", "Docker"],
  },
  {
    company: "Indiacharts",
    role: "Backend Developer Intern",
    period: "Nov 2024 — Jan 2025",
    summary: "Re-architected real-time analytics backend for high-throughput stock data processing and indicator computation.",
    details: [
      "Re-architected the real-time analytics backend to handle high-throughput OHLC data for 3,000+ stocks, enabling consistent sub-second indicator computation during peak market hours.",
      "Built scalable pipelines to compute 100+ technical indicators across multiple timeframes, balancing accuracy, latency, and system cost using distributed workers and optimized vectorized processing.",
    ],
    links: [],
    logo: "/indiacharts.png",
    companyWebsite: "https://indiacharts.com",
    companyTwitter: "https://twitter.com/indiacharts",
    tags: ["Python", "FastAPI", "Redis", "PostgreSQL", "Polars ", "Pandas", "WebSockets", "Docker"],
  },
]

export const stack = ["TypeScript", "Next.js", "React Server Components", "SWR", "Tailwind CSS", "shadcn/ui", "Vercel"]

export const blogs = [
  {
    title: "High level architecture of real-time voice agents",
    description: "Design and implementation of scalable real-time voice applications.",
    date: "Aug 20, 2025",
    link: "https://medium.com/@tyagishashank118/high-level-architecture-of-real-time-voice-agents-ddcedb251fc4"
  },
  {
    title: "Monitoring Microservices on a Budget: Our Journey with SigNoz",
    description: "How we implemented observability in our microservices architecture without breaking the bank.",
    date: "Sept 22, 2025",
    link: "https://medium.com/@tyagishashank118/monitoring-microservices-on-a-budget-our-journey-with-signoz-9b16ce02f778",
  },
  {
    title: "Change Data Capture with Debezium and PostgreSQL",
    description: "How we built and utilized the CDC feature of postgres to build real-time data pipelines.",
    date: "Oct 5, 2025",
    link: "https://medium.com/@tyagishashank118/real-time-change-data-capture-with-debezium-and-postgresql-50f3db656ca5",
  },
]
